### ISSUE TITLE
File name with a colon

### ISSUE THREAD

**Issue by garybuckle** [keastudio/pangea#19]
Using a colon (:) as the starter for a filename is prohibited in MacOS ([Apple Discusions](https://discussions.apple.com/thread/7540284)) possibly also in Windows and Linux. We should  replace the colon with [] as suggested by Jake F.
at src/dev.ts
`const substitutedPath = path.replace(
                /\/:([a-z]+)/g,
                (_match, capturedGroup1) => params[capturedGroup1] === ''
                  ? '/'
                  : '/' + params[capturedGroup1].replaceAll('/', '')
              )`

**Comment by jakefb** [comment]
Hey @garybuckle, thanks for reporting this. I have fixed this in the [1.0.0-rc.15](https://github.com/keastudio/pangea/releases/tag/1.0.0-rc.15) release. This makes it a requirement to use square brackets instead of a colon for dynamic routing.

Note, any sites using the old colon syntax will need to be updated to the square bracket syntax.
